name: CMake

on:
  push

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install LLVM
      run: |
        sudo apt-get remove llvm-12 clang-12 clang-13 llvm-13 libclang-13-dev
        sudo apt-get install -y llvm clang libclang-dev llvm-14-tools llvm-dev
        sudo ln -s `which FileCheck-14` /usr/bin/FileCheck
        pip install lit

    - name: Test
      working-directory: ${{github.workspace}}/dotlink
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        lit -vv ${{github.workspace}}/dotlink/test
